### ISSUE TITLE
Ejercicio de MySQL (Aprox. 40 min)

### ISSUE THREAD

**Issue by coderdiaz** [Bedu-Tech/FSBT-08-2018-mysql#1]
Crear un modelo de datos para identificar entidades y atributos de una aplicación de almacenamiento musical.

Tres entidades principales deben ser:
- Tracks
- Artists
- Albums

Puedes guiarte a través de aplicaciones como Spotify, Soundcloud, iTunes Music, etc.

*Recuerda que cada entidad debe tener un identificador y una llave primaria.*

**Comment by davidtoris** [comment]
Ricardo Zuñiga / Jonathan López / David Toris

Usuarios
----
id INT PRIMARY_KEY NOT_NULL
Usuario VARCHAR(30) NOT_NULL  
password VARCHAR(50) NOT_NULL
tipo VARCHAR(30) NOT_NULL
correo VARCHAR(30) NOT_NULL
ultimo_login TIMESTAMP NOT_NULL


Albums
----
id INT PRIMARY_KEY NOT_NULL
album VARCHAR(30) NOT_NULL
artista INT FOREYGN_KEY NOT_NULL


Playlist
---
id INT PRIMARY_KEY NOT_NULL
tipo VARCHAR(30) NOT_NULL


Canciones
----
id INT PRIMARY_KEY NOT_NULL
Playlist INT FOREYGN_KEY NOT_NULL
album INT FOREYGN_KEY NOT_NULL
cancion VARCHAR(30) NOT_NULL
artista INT FOREYGN_KEY NOT_NULL
tiempo FLOAT NOT_NULL


Artistas
----
id INT PRIMARY_KEY NOT_NULL
Artista INT FOREYGN_KEY NOT_NULL
Genero VARCHAR(30) NOT_NULL
album INT FOREYGN_KEY NOT_NULL

**Comment by alankimo** [comment]
### Mario / Alan / Daniel


CREATE TABLE 
'artistas'(
id_artista unsigned INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nombre varchar(100) NOT NULL,
genero varchar(35) NOT NULL,
bios MEDIUMTEXT,
score_mensual INT,
seguidores INT,
links MEDIUMTEXT,
imagenes MEDIUMTEXT,
popularidad INT,
);

CREATE TABLE
'album'(
id_album unsigned INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
titulo varchar(100) NOT NULL,
fecha_lanzamiento DATE NOT NULL,
cover MEDIUMTEXT,
genero varchar(35) NOT NULL,
id_artista unsigned INT NOT NULL AUTO_INCREMENT,
);

CREATE TABLE
'canciones'( 
id_canciones unsigned INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
titulo varchar(100) NOT NULL,
duracion  INT,
numero_track INT,
popularidad INT,
);

**Comment by davidtoris** [comment]
[Modelo Spotify.pdf](https://github.com/Bedu-Tech/FSBT-08-2018-mysql/files/2948737/Modelo.Spotify.pdf)
