### ISSUE TITLE
Ejercicio 2 de MySQL (Aprox. 40 min)

### ISSUE THREAD

**Issue by coderdiaz** [Bedu-Tech/FSBT-08-2018-mysql#2]
Crear el modelo Entidad-Relación (ER) utilizando workbench, basándose en las entidades y atributos definidos por el equipo.

En este punto puedes hacer uso de todos los campos o únicamente los más importantes que consideres para que tu aplicación funcione.

Nota: Al menos tu modelo debería tener una relación n-n (muchos a muchos).

**Comment by alankimo** [comment]
### Modelo de QuesadillaMusic

[QuesadillaMusic.mwb.zip](https://github.com/Bedu-Tech/FSBT-08-2018-mysql/files/2948733/QuesadillaMusic.mwb.zip)

**Comment by mjohar30** [comment]
[Practica.zip](https://github.com/Bedu-Tech/FSBT-08-2018-mysql/files/2948739/Practica.zip)
